---
metadata:
    processor: unset

routing-policy:
    _process: not_implemented
    defined-sets:
        _process: not_implemented
        neighbor-sets:
            _process: not_implemented
            neighbor-set:
                _process: not_implemented
                config:
                    _process: not_implemented
                    address:
                        _process: not_implemented
                    name:
                        _process: not_implemented
                name:
                    _process: not_implemented
                state:
                    _process: not_implemented
        prefix-sets:
            _process: not_implemented
            prefix-set:
                _process: not_implemented
                config:
                    _process: not_implemented
                    mode:
                        _process: not_implemented
                    name:
                        _process: not_implemented
                name:
                    _process: not_implemented
                prefixes:
                    _process: not_implemented
                    prefix:
                        _process: not_implemented
                        config:
                            _process: not_implemented
                            ip-prefix:
                                _process: not_implemented
                            masklength-range:
                                _process: not_implemented
                        ip-prefix:
                            _process: not_implemented
                        masklength-range:
                            _process: not_implemented
                        state:
                            _process: not_implemented
                state:
                    _process: not_implemented
        tag-sets:
            _process: not_implemented
            tag-set:
                _process: not_implemented
                config:
                    _process: not_implemented
                    name:
                        _process: not_implemented
                    tag-value:
                        _process: not_implemented
                name:
                    _process: not_implemented
                state:
                    _process: not_implemented
    policy-definitions:
        _process: not_implemented
        policy-definition:
            _process: not_implemented
            config:
                _process: not_implemented
                name:
                    _process: not_implemented
            name:
                _process: not_implemented
            state:
                _process: not_implemented
            statements:
                _process: not_implemented
                statement:
                    _process: not_implemented
                    actions:
                        _process: not_implemented
                        config:
                            _process: not_implemented
                            policy-result:
                                _process: not_implemented
                        state:
                            _process: not_implemented
                    conditions:
                        _process: not_implemented
                        config:
                            _process: not_implemented
                            call-policy:
                                _process: not_implemented
                            install-protocol-eq:
                                _process: not_implemented
                        match-interface:
                            _process: not_implemented
                            config:
                                _process: not_implemented
                                interface:
                                    _process: not_implemented
                                subinterface:
                                    _process: not_implemented
                            state:
                                _process: not_implemented
                        match-neighbor-set:
                            _process: not_implemented
                            config:
                                _process: not_implemented
                                match-set-options:
                                    _process: not_implemented
                                neighbor-set:
                                    _process: not_implemented
                            state:
                                _process: not_implemented
                        match-prefix-set:
                            _process: not_implemented
                            config:
                                _process: not_implemented
                                match-set-options:
                                    _process: not_implemented
                                prefix-set:
                                    _process: not_implemented
                            state:
                                _process: not_implemented
                        match-tag-set:
                            _process: not_implemented
                            config:
                                _process: not_implemented
                                match-set-options:
                                    _process: not_implemented
                                tag-set:
                                    _process: not_implemented
                            state:
                                _process: not_implemented
                        state:
                            _process: not_implemented
                    config:
                        _process: not_implemented
                        name:
                            _process: not_implemented
                    name:
                        _process: not_implemented
                    state:
                        _process: not_implemented
