---
metadata:
    processor: unset

local-routes:
    _process: not_implemented
    local-aggregates:
        _process: not_implemented
        aggregate:
            _process: not_implemented
            state:
                _process: not_implemented
                discard:
                    _process: not_implemented
                prefix:
                    _process: not_implemented
                set-tag:
                    _process: not_implemented
    static-routes:
        _process: not_implemented
        static:
            _process: not_implemented
            next-hops:
                _process: not_implemented
                next-hop:
                    _process: not_implemented
                    interface-ref:
                        _process: not_implemented
                        state:
                            _process: not_implemented
                            interface:
                                _process: not_implemented
                            subinterface:
                                _process: not_implemented
                    state:
                        _process: not_implemented
                        index:
                            _process: not_implemented
                        metric:
                            _process: not_implemented
                        next-hop:
                            _process: not_implemented
                        recurse:
                            _process: not_implemented
            state:
                _process: not_implemented
                prefix:
                    _process: not_implemented
                set-tag:
                    _process: not_implemented
