---
_process: unnecessary
areas:
    _process: unnecessary
    area:
        _process:
          - path: area
            key: name
        config:
            _process: unnecessary
            identifier:
                _process:
                  - pre: "{{ area_key }}"
        identifier:
            _process: unnecessary
        interfaces:
            _process: unnecessary
            interface:
                _process:
                  - path: interface
                    key: name
                config:
                    _process: unnecessary
                    authentication-type:
                        _process:
                          - path: authentication.md5.name
                            post: "md5"
                          - path: "authentication.simple-password"
                            post: "simple-password"
                          - path: authentication
                            present: false
                            post: "none"
                    hide-network:
                        _process: not_implemented
                    id:
                        _process: not_implemented
                    metric:
                        _process:
                          - path: metric
                    multi-area-adjacency-primary:
                        _process: not_implemented
                    network-type:
                        _process:
                          - path: "interface-type"
                            regexp: "(?P<value>\\w+)"
                            map: 
                                p2p: POINT_TO_POINT_NETWORK
                                # p2mp not supported in Openconfig model
                                # return p2p to avoid the error
                                p2mp: POINT_TO_POINT_NETWORK
                                nbma: NON_BROADCAST_NETWORK
                          - path: "interface-type"
                            post: BROADCAST_NETWORK
                            present: false
                    passive:
                        _process:
                          - path: passive
                            present: true
                    priority:
                        _process:
                          - path: priority
                id:
                    _process:
                      - pre: "{{ interface_key }}"
                interface-ref:
                    _process: not_implemented
                    config:
                        _process: not_implemented
                        interface:
                            _process: not_implemented
                        subinterface:
                            _process: not_implemented
                    state:
                        _process: not_implemented
                lsa-filter:
                    _process: not_implemented
                    config:
                        _process: not_implemented
                        all:
                            _process: not_implemented
                    state:
                        _process: not_implemented
                mpls:
                    _process: not_implemented
                    config:
                        _process: not_implemented
                        traffic-engineering-metric:
                            _process: not_implemented
                    igp-ldp-sync:
                        _process: not_implemented
                        config:
                            _process: not_implemented
                            enabled:
                                _process: not_implemented
                            post-session-up-delay:
                                _process: not_implemented
                        state:
                            _process: not_implemented
                    state:
                        _process: not_implemented
                neighbors:
                    _process: not_implemented
                    neighbor:
                        _process: not_implemented
                        config:
                            _process: not_implemented
                            metric:
                                _process: not_implemented
                            router-id:
                                _process: not_implemented
                        router-id:
                            _process: not_implemented
                        state:
                            _process: not_implemented
                state:
                    _process: not_implemented
                timers:
                    _process: unnecessary
                    config:
                        _process: unnecessary
                        dead-interval:
                            _process:
                              - path: "dead-interval"
                        hello-interval:
                            _process:
                              - path: "hello-interval"
                        retransmission-interval:
                            _process:
                              - path: "retransmit-interval"
                    state:
                        _process: not_implemented
        lsdb:
            _process: not_implemented
        mpls:
            _process: not_implemented
            config:
                _process: not_implemented
                traffic-engineering-enabled:
                    _process: not_implemented
            state:
                _process: not_implemented
        state:
            _process: not_implemented
        virtual-links:
            _process: not_implemented
            virtual-link:
                _process: not_implemented
                config:
                    _process: not_implemented
                    remote-router-id:
                        _process: not_implemented
                remote-router-id:
                    _process: not_implemented
                state:
                    _process: not_implemented
global:
    _process: unnecessary
    config:
        _process: not_implemented
        hide-transit-only-networks:
            _process: not_implemented
        igp-shortcuts:
            _process: not_implemented
        log-adjacency-changes:
            _process: not_implemented
        router-id:
            _process:
              - path: "routing-options.router-id"
                from: "network_instance.{{ network_instance_key }}"
        summary-route-cost-mode:
            _process: not_implemented
    graceful-restart:
        _process: not_implemented
        config:
            _process: not_implemented
            enabled:
                _process: not_implemented
            helper-only:
                _process: not_implemented
        state:
            _process: not_implemented
    inter-area-propagation-policies:
        _process: not_implemented
        inter-area-propagation-policy:
            _process: not_implemented
            config:
                _process: not_implemented
                default-import-policy:
                    _process: not_implemented
                dst-area:
                    _process: not_implemented
                import-policy:
                    _process: not_implemented
                src-area:
                    _process: not_implemented
            dst-area:
                _process: not_implemented
            src-area:
                _process: not_implemented
            state:
                _process: not_implemented
    mpls:
        _process: not_implemented
        config:
            _process: not_implemented
            traffic-engineering-extensions:
                _process: not_implemented
        igp-ldp-sync:
            _process: not_implemented
            config:
                _process: not_implemented
                enabled:
                    _process: not_implemented
                post-session-up-delay:
                    _process: not_implemented
            state:
                _process: not_implemented
        state:
            _process: not_implemented
    state:
        _process: not_implemented
    timers:
        _process: unnecessary
        lsa-generation:
            _process: not_implemented
            config:
                _process: not_implemented
                initial-delay:
                    _process: not_implemented
                maximum-delay:
                    _process: not_implemented
            state:
                _process: not_implemented
        max-metric:
            _process: not_implemented
            config:
                _process: not_implemented
                include:
                    _process: not_implemented
                set:
                    _process: not_implemented
                timeout:
                    _process: not_implemented
                trigger:
                    _process: not_implemented
            state:
                _process: not_implemented
        spf:
            _process: unnecessary
            config:
                _process: unnecessary
                initial-delay:
                    _process:
                      - path: "spf-options.delay"
                maximum-delay:
                    _process:
                      - path: "spf-options.holddown"
            state:
                _process: not_implemented
